MySite/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'MySite'

urlpatterns = [
    path('index.html', views.index, name='index'),

    path('portfolio.html', views.portfolio, name='portfolio'),

    path('PostList.html', views.PostList, name='PostList'),

    path('tag/<slug:tag_slug>/', views.PostList, name='PostList_by_tag'),

    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.PostDetail, name='PostDetail'),

    path('feed/', LatestPostsFeed(), name='post_feed'),

    path('projects.html', views.Projects.as_view(), name='Projects'),

    path('<slug:slug>/', views.ProjectDetail.as_view(), name='ProjectDetail'),

    path('contact.html', views.Contact, name='Contact'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # admin's url
    path('admin/', admin.site.urls),

    # apps url
    path('', include('MySite.urls', namespace='MySite')),
    # path('MySite/', include('MySite.urls', namespace='MySite')),

    # ckeditor path
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset() \
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, unique_for_date='publish')
    featured_image = models.ImageField(upload_to='featuredImage/')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('MySite:PostDetail', args=[self.publish.year,
                                                  self.publish.month,
                                                  self.publish.day,
                                                  self.slug])


class Project(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, unique_for_date='publish')
    featured_img = models.ImageField(upload_to='ProjectImages')
    body = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

MySite/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

MySite/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Project
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm
from django.views import generic
from taggit.models import Tag
from django.db.models import Count
from django.core.mail import send_mail


# Create your views here.
def index(request):
    return render(request, 'index.html', {})


def portfolio(request):
    return render(request, 'portfolio.html', {})


def PostList(request, tag_slug=None):
    posts = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'PostList.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag, })


def PostDetail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day, )

    # list of active comments
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # comment posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create a new comment but do not save in the database yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            new_comment.post = post
            # save the comment to the database
            new_comment.save()

    else:
        comment_form = CommentForm

    # list of similar functions
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                    .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'PostDetail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


class Projects(generic.ListView):
    queryset = Project.objects.filter(status='publish').order_by('-publish')
    template_name = 'projects.html'
    paginate_by = 3


class ProjectDetail(generic.DetailView):
    model = Project
    template_name = 'ProjectDetail.html'


def Contact(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']

        # sending emails
        send_mail(
            'message from' + message_name, # subject
            message, # message
            message_email , # from
            ['jumaantony840@gmail.com'], # to
        )

        return render(request, 'contact.html',
                      {'message_name': "Hello " + message_name + "! We will resopnd to you shortly..."})
    else:
        return render(request, 'contact.html', {})

MySite/templates/PostDetail.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}
{% block title%} Detailed Post {% endblock %}


{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/post-detail.css' %}">

<div id="main">

    <body>
        <div class="main-cont">
            <div class="post-cont">
                <h1 class="blog-title">{{ post.title }}</h1>
				<hr>
                <p class="author">By: {{ post.author }}, {{ post.publish }}</p>
				<p class="detailed"> {{ post.body|safe |linebreaks}} </p>

					<br><br><br>
                	<span class="share" >
					  <h3>Share</h3>

						<h6 id="share-btns" style="display: inline-block;">{% post_to_facebook object_or_url %}</h6>
						<h6 id="share-btns" style="display: inline-block;">{% post_to_twitter "New Post: {{post.title }}. Check it out!" object_or_url %}</h6>
						<h6 id="share-btns" style="display: inline-block;">{% post_to_linkedin object_or_url %}</h6>
						<h6 id="share-btns" style="display: inline-block;">{% post_to_whatsapp object_or_url "" %}</h6>

            		</span>

					{% with comments.count as total_comments %}

						<p class="comments-count"> {{ total_comments }}  Thought {{ total_comments|pluralize}}</p>
					
					{% endwith %}

					{% for comment in comments %}

						<div class="comment-info">
							<p class="comment-author">
								Comment {{ forloop.counter }} by {{ comment.name}}
							</p>
							<p class="comment-body"> 
								{{ comment.body }}
								<button type="POST" class="show-reply-form"  onclick="Openreply()">
									Reply
								</button>
							</p>

							{% for reply in comment.replies.all %}
								<div class="reply-info">
									<p class="reply-author">
									{{ reply.name }} / {{ reply.created }}
									</p>
									<p class="reply-body">
									{{ reply.body }}
									</p>
								</div>
							{% endfor %}

							  <div class="reply-cont" id="reply-form">
								<h3 class="leave-comment">Leave a Reply</h3>
			
								<form method="POST">
								  {{ comment_form.as_p }}
								  {% csrf_token %}

								  <input type="hidden" name="parent_id" value="{{ comment.id }}">
								  

								  <button type="submit" class="show-reply-form" id="hide-reply-form"
										  class="comment-btn">Reply</button>

								 </form>
							  </div>
						</div>
					
					{% endfor %}

					<hr>
					
					{% if new_comment %}
						<h3>Your comment has been delivered and waiting for an approval </h3>
					{% else %}

						<h3 class="leave-comment">Leave a comment</h3>

						<div class="comment-form">
							<form method="post">
	
								{{ comment_form.as_p }}
								{% csrf_token %}
								
								<button type="submit" class="comment-btn">Comment</button>
							</form>
							
						</div>
					{% endif %}
            </div>


            <div class="side-cont">

            	<div >
            		<h2 class="other-info">Related Posts</a></h2>
						{% for post in similar_posts %}
							<p>
								<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
							</p>
						{% empty %}
							There are no similar posts yet
						{% endfor %}

            	</div>


            </div>

        </div>
	</body>
	
    {% include "footer.html" %}
</div>n 
<script type="text/javascript">
function Openreply() {
var x = document.getElementsByClassName('show-reply-form');
if (x.style.display === "none") {
   x.style.display = "block";
} else {
  x.style.display = "none";
}
}
</script>
{% endblock %}

MySite/templates/PostList.html
{% extends 'base.html' %}
{% load static %}
{% load mysite_tags %}
{% load taggit_templatetags2_tags %}
{% get_taglist as tags for 'MySite.Post:tags' %}
{% block title%} Blog Posts {% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/post-list.css' %}">

<div id="main">
  <body>
    <div class="Img-header"><h1 class="heading">My Blog</h1></div>

    <div class="main-cont">
        <div class="post-cont">
            <div class="single-post">

                {% if tag %}
                <h1> Posts Tagged With: {{ tag.name }}</h1>
                {% endif %}

                {% for post in posts %}
                <img class="featured-img" src="{{ post.featured_image.url }}">
                <div class="post-body">
                    <h2 class="post-title">
                        <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                        </a>
                    </h2>

                    <p>Tagged as:
                        {% for tag in post.tags.all %}
                            <a href="{% url 'MySite:PostList_by_tag' tag.slug %}">
                                {{ tag.name }}
                            </a>
                        {% endfor %}
                    </p>

                    <div class="author-date">
                       <p> Published {{ post.publish }} by {{ post.author }}</p>
                     </div>
                    <p class="post-content">
                        {{ post.body |safe | truncatewords:50 | linebreaks  }}
                     </p>
                     <button class="read-more"><a href="{{ post.get_absolute_url }}"> READ MORE → </a> </button>
                </div>
                {% endfor %}
                {% include "pagination.html" with page=posts %}
            </div>

        </div>

        <div class="side-cont">

            <div class="search"><h2 class="side-cont-title">Search</h2>
                <input type="text" name="search" placeholder="Search for ..." class="search-for">
                <button class="go">Go</button>
            </div>

            <br>
            <h2 class="side-cont-title">Total posts written: {% total_posts %}</h2>

            <div class="latest-posts"> 
                <h2 class="side-cont-title">Latest Posts</h2>
                {% show_latest_posts 6%}
            </div>

            <div class="categories"> <h2 class="side-cont-title">Tags</h2>
                    <ul>
                        {% for Tag in tags %}
                            <li>{{tag}} ({{tag.num_times}})</li>
                        {% endfor %}
                    </ul>

            </div> 

            <div class="tags"><h2 class="side-cont-title">Most Commented Posts</h2>
                {% get_most_commented_posts as most_commented_posts %}
                {% for post in most_commented_posts %}
                  <p class="sub-cat"><a href="{{ post.get_absolute_url }}" >{{ post.title }} Integration</a></p>
                {% endfor %}
            </div>

        </div>
    </div>
  </body>
  <div style="margin-bottom: 30%;"> </div>
{% include "footer.html" %}
</div>
{% endblock %}

MySite/templates/base.html
{% load static %}

<html>
<head>
	<title>{% block title%} {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <script src="https://use.fontawesome.com/05c22190f5.js"></script>

    <link rel="shortcut icon" href="{% static 'images/logo.jpg' %} ">

</head>
<body>
<header>
	<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <br>
  <a href="{% url 'MySite:index' %}">
      <i class="fa fa-home" ></i> Home
  </a>
  <a href="{% url 'MySite:portfolio' %}">
      <i class="fa fa-user"></i> Portfolio
  </a>
  <a href="{% url 'MySite:PostList' %}">
      <i class="fa fa-pencil-square-o"></i >Blog
  </a>
  <a href="{% url 'MySite:Projects' %}">
      <i class="fa fa-tasks"></i> Projects
  </a>
  <a href="{% url 'MySite:Contact' %}">
      <i class="fa fa-address-card"></i> Contact Me
  </a>
</div>

<!-- Use any element to open the sidenav -->
<span onclick="openNav()"><i class="fa fa-bars fa-2x" id="menu-bar"></i></span>
</header>

{% block content %}



{% endblock %}


</body>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</html>

MySite/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load mysite_tags %}
{% block title%} Contact Me {% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">

<div id="main">
    <div class="cnct-header"><h1 class="cntct-head">Get In Touch With Me</h1></div>
  <body>
    <div>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1021393.4635832297!2d34.627645042213445!3d0.013033031194875134!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182aa437ad4ac81d%3A0x2012a439d6248dd2!2sKisumu!5e0!3m2!1sen!2ske!4v1597886292295!5m2!1sen!2ske" class="map"></iframe>
    </div>

    <div class="contact-cont">
        <div class="contct">
          <h3> <i class="fa fa-address-card-o" aria-hidden="true"></i> Address </h3>
            <p>Kisumu, 40100, Kenya</p><br>
          <h3> <i class="fa fa-phone" aria-hidden="true"></i> Phone</h3>
            <p>+254 742 491942</p><br>
          <h3> <i class="fa fa-envelope-o" aria-hidden="true"></i> Email</h3>
            <p>jumaantony840@gmail.com</p>
        </div>

        <div class="form">
          <h1>Get In Touch</h1>
          <h6>{{message_name}}</h6>
          <br>

          <form action="{% url 'MySite:Contact' %}" method="POST">
            {% csrf_token %}

            <input type="text" name="message-name"  placeholder="Your Name" class="contct-name">
            
            <input type="email" name="message-email"  placeholder="Your Email" class="contct-email">
            <br>

            <textarea name="message" placeholder="Your Message" class="contct-message"></textarea>
            <br>
            
            <button type="submit" class="btn-message ">Send Message</button>
          </form>

        </div>
    </div>

    {% include "footer.html" %}
  </body>

{% endblock %}

MySite/templates/footer.html
{% load static %}
{% load mysite_tags %}
<link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
<footer>
          <div class="footer-items">
            <div class="Sect1">
              <div class="logo"></div>
              <div class="logo-info">
                <h4>Juma Antony</h4>
                <p>So, you wanna learn about me? Well… it’s complicated and pretty juicy. I don’t hold much back..<a href="portfolio.html" class="read"> Read More</a></p>
              </div>
              <h4 class="follow">Follow</h4>
              <a href="https://www.facebook.com/profile.php?id=100011079511148">
                  <i class="fa fa-facebook" id="social-media-btns"></i>
              </a>
              <a href="https://twitter.com/jumaantony12">
                  <i class="fa fa-twitter" id="social-media-btns"></i>
              </a>
              <a href="https://www.linkedin.com/in/antony-juma-746641189/">
                  <i class="fa fa-linkedin-square" id="social-media-btns"></i>
              </a>

            </div>

            <div class="Sect2">
              <h4 class="foot-1">Latest Posts</h4>
              {% show_latest_posts 4 %}
                <br>

            </div>

            <div class="Sect3">
              <h4 class="foot-1">Recent Projects</h4>
                 {% show_latest_projects 4 %}
              
              <br>
            </div>

            <div class="Sect4">
              <h4 class="foot-1">Pages</h4>
                <div class="foot-pages">
                  <a href="{% url 'MySite:index' %}">
                    Home
                </a>
                <a href="{% url 'MySite:portfolio' %}">
                     Portfolio
                </a>
                <a href="{% url 'MySite:PostList' %}">
                    Blog
                </a>
                <a href="{% url 'MySite:Projects' %}">
                     Projects
                </a>
                <a href="{% url 'MySite:Contact' %}">
                     Contact Me
                </a>
                </div>
              <br><br>
              <p>Subscribe to my latest newsletter, <br>
              To receive latest updates</p> <br>
              <div class="subscribe-body">
                <div class="input-group">
                  <input type="text" name="Subscribe" class="form-control" placeholder="Email address">
                  <button class="btn"> <i class="fa fa-paper-plane fa-1.8x"></i></button>
                </div>
                <buttton class="rss">
                  <a href="{% url 'MySite:post_feed' %}"><i class="fa fa-rss fa-2x"></i></a>
                </buttton>
              </div>
            </div>
          </div>
</footer>

MySite/templates/index.html
{% extends "base.html" %}
{% load static %}
{%block title%} Juma Antony {% endblock %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<div id="main">
  <body>
	<main id="headings">
        <div class="image"> </div>
        <div class="overlay"></div>

        <h1 class="lg-heading">
            Juma <span class="text-secondary">Antony</span>
        </h1>

        <h2 class="tagline">
            Web Developer, Programmer
        </h2>

        <center class="more">
            <button class="portfolio"> <a href="portfolio.html"> portfolio</a> </button>
            <button class="skills"> <a href="portfolio.html"> skills</a> </button>
            <button class="blog"> <a href="blog.html"> Blog</a> </button>
            <button class="MyWork"> <a href="project.html"> Projects</a> </button>
        </center>

        </main>
    </body>
</div>

{% endblock %}

MySite/templates/latest_posts.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/post-list.css' %}">

<ul>
    {% for post in latest_posts %}
        
        <p class="sub-cat"><a href="{{ post.get_absolute_url }}">{{post.title}}</a></p>
        
    {% endfor %}
</ul>

MySite/templates/latest_projects.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/post-list.css' %}">

<ul>
    {% for project in latest_projects %}

        <p class="sub-cat"><a href="{% url 'MySite:ProjectDetail' project.slug %}">{{project.title}}</a></p>

    {% endfor %}
</ul>

MySite/templates/pagination.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/post-list.css' %}">


    <span class="pagination">

        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}" class="step-links"> Previous</a>
        {% endif %}

        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}
        </span>

        {% if page.has_next %}
        <a href="?page={{page.next_page_number}}" class="step-links">Next</a>
        {% endif %}
    </span>

MySite/templates/projects.html
{% extends 'base.html' %}
{% load static %}
{% load mysite_tags %}
{% block title%} My works {% endblock %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/projects.css' %}">
    <div id="main">
        <div class="Img-header"><h1 class="heading">Buy me a Coffee,<br> Let's Talk about your Project</h1></div>
    
        <h1 class="my-work">My Work</h1>
        <div class="project-cont">

          {% for project in project_list  %}
        
            <div class="proj-cont">
                <img src="{{ project.featured_img.url }}" alt="featured-img" class="featured">
                <a href="{% url 'MySite:ProjectDetail' project.slug %}"><h1>{{ project.title }}</h1></a>
                <p class="description">{{ project.body |safe | truncatewords:50 | linebreaks }}</p>
                <br>
                <a href="{% url 'MySite:ProjectDetail' project.slug %}" class="view-proj">Project description</a>
                <br>
            </div>

          {% endfor %}

        </div>
        
        {% if is_paginated %}
          <div class="pagination">
          <span>
            {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}" class="step-links"> Previous</a>
            {% endif %}
              <!--<span class="current">
              Page 1 of 5
              </span> -->
            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}" class="step-links">Next</a>
            {% endif %}
          </span>
          </div>
        {% endif %}
    
        <h1 class="client">Happy clients</h1>
        <div class="slide-show">
            <div class="testimonial">
            <img src="{% static 'images/logo.jpg' %}" alt="" class="client-img">
            <p class="message">Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, atque fugit unde quas minima mollitia aliquam iste dolorem consequuntur voluptas ut iusto, tempora dolorum cumque corporis ipsam laborum, perferendis sed.</p>
            <h3 class="client-name">Wicked</h3>
            <h3 class="client-org">Cybernetic Systems</h3>
            </div>
    
            <div class="testimonial">
            <img src="{% static 'images/blog-1.jpg' %}" alt="" class="client-img">
            <p class="message">Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, atque fugit unde quas minima mollitia aliquam iste dolorem consequuntur voluptas ut iusto, tempora dolorum cumque corporis ipsam laborum, perferendis sed.</p>
            <h3 class="client-name">Lydia</h3>
            <h3 class="client-org">Lyomu Palour</h3>
            </div>
    
            <div class="testimonial">
            <img src="{% static 'images/blog-2.jpg' %}" alt="" class="client-img">
            <p class="message">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora voluptatum, repellat quidem at ipsum quaerat possimus ipsam explicabo non voluptatem rem sed recusandae enim fugiat, sapiente est iusto sint ab.</p>
            <h3 class="client-name">Willis</h3>
            <h3 class="client-org">The Kandiz Cafe</h3>
            </div>
    
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
    
        <div class="dot-cont">
            <div class="dot">
            <i id="dot-nav" class="fa fa-dot-circle-o" onclick="currentSlide(1)"></i>
            </div>
            <div class="dot">
            <i id="dot-nav" class="fa fa-dot-circle-o" onclick="currentSlide(2)"></i>
            </div>
            <div class="dot">
            <i id="dot-nav" class="fa fa-dot-circle-o" onclick="currentSlide(3)"></i>
            </div>
        </div>            

    {% include "footer.html" %}
    </div>
    <script>
        var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
      showSlides(slideIndex += n);
    }

    function currentSlide(n) {
      showSlides(slideIndex = n);
    }

    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("testimonial");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) {slideIndex = 1}
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
          dots[i].className = dots[i].className.replace(" active", "");
        }
      slides[slideIndex-1].style.display = "block";
      dots[slideIndex-1].className += " active";
    }
    </script>
{% endblock %}